version: '3.7'

services:

  postgres-adler-local:
    image: postgres:12
    container_name: postgres-adler-local
    restart: on-failure
    environment:
      POSTGRES_DB: adler-local-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432