name: Tests

on:
  push:
    branches-ignore:
      - 'release*'

jobs:

  caching:
    name: Cache Maven packages
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven Verify
        run: mvn -B clean verify

  compile:
    name: Compile
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B package

  artifact:
    name: Save artifacts

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir developing && cp services/mobile-service/target/*.jar developing
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: developing
